[build]
command = "npm run build"
publish = "dist"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

#####################
#  Redirect Rules   #
#####################
[[redirects]]
from = "/*"
to = "/index.html"
status = 200